version: '3.8'

services:
  architecture:
    build:
      context: ./architecture
    ports:
      - "8000:8000"  # Expose service1 on port 8000

  blog:
    build:
      context: ./blog
    ports:
      - "8001:8000"  # Expose service2 on port 8001

  it:
    build:
      context: ./it
    ports:
      - "8002:8000"  # Expose service3 on port 8002

  user:
    build:
      context: ./user
    ports:
      - "8003:8000"  # Expose service4 on port 8003

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Map your Nginx config file
    ports:
      - "80:80"
    depends_on:
      - architecture
      - blog
      - it
      - user